// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iurpdcgvydcoaetphgpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1cnBkY2d2eWRjb2FldHBoZ3B3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4Nzc0MDUsImV4cCI6MjA2ODQ1MzQwNX0.MutPGGp-jWs8bS0YB6yZrFS7hgqnB6KXov9zJ5YjLc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});